# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automation Test Execution 

on:
  push:
    branches: [ main ]

jobs:
  tests:
    name: Test Execution
    runs-on: windows-latest
    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
    - name: Setting up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: command prompt instead of PS   
      run: cmd
    - name: Check node version
      run: node -v
    - name: Check npm version
      run: npm -v
    - name: Install dependencies    
      run: npm ci
    - name: Install Playwright
      run: npx playwright install
    - name: Creating test suite  
      run: npm run create:suite SHEET=Regression
    - name: Test execution
      run: npm test
